build: bump libnetfilter_log dependency
Recent changes to add conntrack info to the NFLOG output plug-in rely on
symbols only present in the headers provided by libnetfilter-log v1.0.2:

    CC       ulogd_inppkt_NFLOG.lo
  ulogd_inppkt_NFLOG.c: In function 'build_ct':
  ulogd_inppkt_NFLOG.c:346:34: error: 'NFULA_CT' undeclared (first use in this function); did you mean 'NFULA_GID'?
     if (mnl_attr_get_type(attr) == NFULA_CT) {
                                    ^~~~~~~~
                                    NFULA_GID
  ulogd_inppkt_NFLOG.c:346:34: note: each undeclared identifier is reported only once for each function it appears in
  ulogd_inppkt_NFLOG.c: In function 'start':
  ulogd_inppkt_NFLOG.c:669:12: error: 'NFULNL_CFG_F_CONNTRACK' undeclared (first use in this function); did you mean 'NFULNL_CFG_F_SEQ'?
     flags |= NFULNL_CFG_F_CONNTRACK;
              ^~~~~~~~~~~~~~~~~~~~~~
              NFULNL_CFG_F_SEQ

Bump the pkg-config version accordingly.

Fixes: f6a615587a10 ("NFLOG: attach struct nf_conntrack")
Fixes: e513a04cd925 ("NFLOG: add NFULNL_CFG_F_CONNTRACK flag")
Signed-off-by: Jeremy Sowden <jeremy@azazel.net>
Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>